(defun setup-env-ebb()
  (interactive)
  (desktop-change-dir "/repo/ebb")
  (desktop-save-mode 1)
  (purpose-load-window-layout 'c++)
  (projectile-run-eshell))

(defun setup-env-c2-carrier()
  (interactive)
  (desktop-change-dir "~/.emacs.d/emacs-sessions/cgci-c2-carrier-resource-enabled")
  (desktop-save-mode 1)
  (purpose-load-window-layout 'c++)
  (projectile-run-eshell))

(defun setup-env-emacsconf()
  (interactive)
  (desktop-change-dir "~/.emacs.d/")
  (desktop-save-mode 1))
(provide 'setup-env)
